FROM docker.io/archlinux/archlinux:latest

ARG BOOTC_VERSION=v1.14.1

# Move pacman mutable state under /usr/lib/sysimage so pacman still works when
# the deployment root is image-managed by bootc/OSTree.
RUN grep "= */var" /etc/pacman.conf | sed "/= *\/var/s/.*=// ; s/ //" | xargs -n1 sh -c 'mkdir -p "/usr/lib/sysimage/$(dirname $(echo $1 | sed "s@/var/@@"))" && mv -v "$1" "/usr/lib/sysimage/$(echo "$1" | sed "s@/var/@@")"' '' && \
    sed -i -e "/= *\/var/ s/^#//" -e "s@= */var@= /usr/lib/sysimage@g" -e "/DownloadUser/d" /etc/pacman.conf

# Arch's container image omits language/help payloads through NoExtract rules.
RUN sed -i 's/^[[:space:]]*NoExtract/#&/' /etc/pacman.conf
RUN --mount=type=tmpfs,dst=/tmp --mount=type=cache,dst=/usr/lib/sysimage/cache/pacman \
    pacman -Sy glibc --noconfirm

RUN --mount=type=tmpfs,dst=/tmp --mount=type=cache,dst=/usr/lib/sysimage/cache/pacman \
    pacman -Syu --noconfirm \
    base \
    cpio \
    dbus \
    dbus-glib \
    dosfstools \
    dracut \
    e2fsprogs \
    git \
    glib2 \
    linux \
    linux-firmware \
    ostree \
    podman \
    shadow \
    skopeo \
    systemd \
    xfsprogs \
    && pacman -S --clean --noconfirm

# Build bootc from source until Arch has a suitable official bootc package.
RUN --mount=type=cache,dst=/root/.cargo/registry --mount=type=cache,dst=/root/.cargo/git \
    pacman -S --noconfirm make rust go-md2man && \
    git clone --branch "${BOOTC_VERSION}" --depth 1 "https://github.com/bootc-dev/bootc.git" /tmp/bootc && \
    make -C /tmp/bootc bin install-all && \
    printf "systemdsystemconfdir=/etc/systemd/system\nsystemdsystemunitdir=/usr/lib/systemd/system\n" > /usr/lib/dracut/dracut.conf.d/30-archlinux-bootc-module.conf && \
    printf 'reproducible=yes\nhostonly=no\ncompress=zstd\nadd_dracutmodules+=" ostree bootc "' > /usr/lib/dracut/dracut.conf.d/30-archlinux-bootc-container-build.conf && \
    dracut --force "$(find /usr/lib/modules -maxdepth 1 -type d -name '[0-9]*' | sort -V | tail -1)/initramfs.img" && \
    pacman -Rns --noconfirm make rust go-md2man && \
    pacman -S --clean --noconfirm && \
    rm -rf /tmp/bootc /tmp/node-compile-cache

RUN sed -i 's|^HOME=.*|HOME=/var/home|' /etc/default/useradd && \
    rm -rf /boot /home /root /usr/local /srv /mnt /var /usr/lib/sysimage/log /usr/lib/sysimage/cache/pacman/pkg && \
    mkdir -p /sysroot /boot /usr/lib/ostree /var /usr/lib/bootc/install && \
    ln -sT sysroot/ostree /ostree && \
    ln -sT var/roothome /root && \
    ln -sT var/srv /srv && \
    ln -sT var/mnt /mnt && \
    ln -sT var/home /home && \
    ln -sT ../var/usrlocal /usr/local && \
    printf "d /var/home 0755 root root -\nd /var/srv 0755 root root -\nd /var/mnt 0755 root root -\nd /var/usrlocal 0755 root root -\nd /var/roothome 0700 root root -\nd /run/media 0755 root root -\n" > /usr/lib/tmpfiles.d/bootc-base-dirs.conf && \
    printf '[composefs]\nenabled = yes\n[sysroot]\nreadonly = true\n' > /usr/lib/ostree/prepare-root.conf && \
    printf '[install.filesystem.root]\ntype = "ext4"\n' > /usr/lib/bootc/install/00-archlinux.toml

LABEL containers.bootc=1
RUN bootc container lint
